### ISSUE TITLE
Add timeout to Jenkins build

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezz_Test#40]
Whatever we do in the Foundation for a timeout we should do to this one: https://github.com/BlackToppStudios/Mezz_Foundation/issues/31

**Comment by crazyfables** [comment]
Unless I'm wrong, they may already have this: https://wiki.jenkins.io/display/JENKINS/Build-timeout+Plugin

**Comment by Sqeaky** [comment]
I belueve we are using this I believe. This requires a piece of code in the Jenkinsfile file to set it. 

Take a look at: https://github.com/BlackToppStudios/Mezz_StaticFoundation/blob/master/Jenkinsfile


The line `timeout(time: 1500, unit: 'SECONDS')` sets the options for that plugin to do it's job. It is not a complex task to complete this ticket, but it does require thoroughness.

**Comment by Sqeaky** [comment]
This is complete and but not updated here.
